
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - name: urlshortener
        image: gcr.io/${GCP_PROJECT}/urlshortener:latest
        ports:
        - containerPort: 8080
